# start a server with `rest -s -a :18080`
locals {
 test = "test"
}
request "basic" {
  url = "http://localhost:18080/hello-world"
  method = "POST"
  headers = {
    "Content-Type" = "application/json"
    "X-Test" = "${locals.test}"
  }
  body = {
    data: "hello world"
  }
  after = <<LUA
    local body = json.decode(rest.res.body)
    print(body.status)
  LUA
}
